# Site
repository: https://qkrgmlwjd39.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Heejung Park
title: Ph.D student in DGIST, South Korea
email: heejungpark@dgist.ac.kr or heejungp@stanford.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# # Social links
# twitter_username: facespics
github_username: qkrgmlwjd39
# # stackoverflow_username: "00000001"
# # dribbble_username: jekyll
# # facebook_username: jekyll
# # flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# # xing_username: jekyll
# # pinterest_username: jekyll
# youtube_username: globalmtb
# # googleplus_username: +jekyll
# # orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: Hi, my name's <mark>Heejung</mark> and I'm a Ph.D student in <a href="https://sites.google.com/view/mispl/home" target="_blank"> Medical Image and Signal Processing Laboratory</a> at Daegu Gyeongbuk Institute of Science and Technology (DGIST) advised by <a href="https://sites.google.com/view/mispl/members/professor" target="_blank"> Prof.Sang Hyun Park</a>. I have extensive experience in medical image processing, specializing in both image registration and segmentation. My current research focuses on solving the challenge of medical image segmentation, specifically addressing the privacy concerns associated with medical data. I am employing federated learning method to develop solutions for organ segmentation, aiming to enhance both accuracy and privacy in medical image.

Keywords: <mark>Federated Learning</mark>, <mark>Medical Image Registration</mark>, <mark>Medical Image Processing</mark>


# content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption: 2020 - Present
        sub_title: <b>Integrated MS&Ph.D Candidate</b>, Department of Robotics and Mechatronics Engineering, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea. 
       
      - layout: left
        caption: 2015 - 2020
        sub_title: <b>Bachelor of Engineering</b>, School of Undergraduate Studies, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.
    
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # title: 
        caption: 2024.07 - 2024.12
        sub_title: <b>Visiting Scholar</b>, <a href="https://cnslab.stanford.edu/" target="_blank"> CNS Lab</a>, Stanford Univ, USA. 

      - layout: left
        caption: 2018.03 - 2018.12
        sub_title: <b>Undergraduate Group Research Program (UGRP)<\b>, <a href="http://abc.dgist.ac.kr/" target="_blank"> ABC Lab</a>, DGIST, South Korea. 

 - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        papertitle: Communication Efficient Federated Learning for Multi-Organ Segmentation via Knowledge Distillation with Image Synthesis
        authors: Kim, S.*, <b>Park, H.*<\b>, Kang, M., Jin, K. H., Adeli, E., Pohl, K. M., & Park, S. H.
        publisher: Under Review
      
      - layout: left
        papertitle: Federated Learning with Knowledge Distillation for Multi-organ Segmentation with Partially Labeled Datasets. 
        authors: Kim, S.*, <b>Park, H.*<\b>, Kang, M., Jin, K. H., Adeli, E., Pohl, K. M., & Park, S. H.
        publisher: Medical Image Analysis (MediA, IF 10.9, JCR<5%)

      - layout: left
        papertitle: A Meta-Learning Approach for Medical Image Registration 
        authors: <b>Park, H*.<\b>, Lee, G. M*., Kim, S., Ryu, G. H., Jeong, A., Sagong, M., & Park, S. H.
        publisher: IEEE 19th International Symposium on Biomedical Imaging (ISBI)

  - title: Awards
    layout: text
    content: 
      - (2023) Outstanding Presentation Award, 37 th Korean Society of Imaging Informatics in Medicine (KIISM)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
