# Site
repository: qkrgmlwjd39.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Heejung Park
title: Ph.D student in DGIST, South Korea
email: heejungpark@dgist.ac.kr
# or heejungp@stanford.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: qkrgmlwjd39
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
 Hi, my name's <mark>Heejung</mark> and I'm a Ph.D. student in the <a href="https://sites.google.com/view/mispl/home" target="_blank">Medical Image and Signal Processing Laboratory</a> at the Daegu Gyeongbuk Institute of Science and Technology (DGIST), advised by <a href="https://sites.google.com/view/mispl/members/professor" target="_blank">Prof. Sang Hyun Park</a>. I have extensive experience in medical image processing, specializing in both <mark>image registration</mark> and <mark>segmentation</mark>. My current research focuses on solving the challenge of medical image segmentation, specifically addressing the privacy concerns associated with medical data. I am employing the <mark>federated learning</mark> method to develop solutions for organ segmentation, aiming to enhance both accuracy and privacy in medical imaging.
  Keywords: <mark>Federated Learning</mark>, <mark>Medical Image Registration</mark>, <mark>Medical Image Processing</mark>

content:
  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: 2020 - Present
        quote: <b>Integrated MS&Ph.D Candidate</b>, Department of Robotics and Mechatronics Engineering, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.
      - layout: left
        border: weak
        title: 2015 - 2020
        quote: Bachelor of Engineering, School of Undergraduate Studies, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.
  - title: Experience
    layout: list
    content:
      - layout: left
        caption: 2024.07 - 2024.12
        sub_title: Visiting Scholar, <a href="https://cnslab.stanford.edu/" target="_blank">CNS Lab</a>, Stanford Univ, USA. 
      - layout: left
        caption: 2018.03 - 2018.12
        sub_title: Undergraduate Group Research Program (UGRP), <a href="http://abc.dgist.ac.kr/" target="_blank">ABC Lab</a>, DGIST, South Korea.
  - title: Publications
    layout: list
    content:
      - layout: top-right
        sub_title: Communication Efficient Federated Learning for Multi-Organ Segmentation via Knowledge Distillation with Image Synthesis
        caption: Kim, S.*, <b>Park, H.*</b>, Kang, M., Jin, K. H., Adeli, E., Pohl, K. M., & Park, S. H.
        description: Under Review
      
      - layout: top-right
        sub_title: Federated Learning with Knowledge Distillation for Multi-organ Segmentation with Partially Labeled Datasets. 
        caption: Kim, S.*, <b>Park, H.*</b>, Kang, M., Jin, K. H., Adeli, E., Pohl, K. M., & Park, S. H.
        description: Medical Image Analysis (MediA, IF 10.9, JCR<5%)

      - layout: top-right
        sub_title: A Meta-Learning Approach for Medical Image Registration 
        caption: <b>Park, H.*</b>, Lee, G. M.*, Kim, S., Ryu, G. H., Jeong, A., Sagong, M., & Park, S. H.
        description: IEEE 19th International Symposium on Biomedical Imaging (ISBI)

  - title: Awards
    layout: text
    content: Outstanding Presentation Award, 37th Korean Society of Imaging Informatics in Medicine (KIISM), 2023

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
